-- System-owned Grammar in Use catalog and legacy knowledge-point compatibility.
CREATE TYPE "KnowledgePointSource" AS ENUM ('legacy', 'grammar_in_use');

ALTER TABLE "Course" ADD COLUMN "grammarBookEditionId" TEXT;

CREATE TABLE "GrammarBookEdition" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "edition" TEXT NOT NULL,
  "officialLevel" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL,
  CONSTRAINT "GrammarBookEdition_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GrammarSection" (
  "id" TEXT NOT NULL,
  "bookEditionId" TEXT NOT NULL,
  "officialTitle" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL,
  CONSTRAINT "GrammarSection_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "KnowledgePoint" (
  "id" TEXT NOT NULL,
  "source" "KnowledgePointSource" NOT NULL,
  "bookEditionId" TEXT,
  "sectionId" TEXT,
  "title" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL,
  CONSTRAINT "KnowledgePoint_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GrammarKnowledgePointUnit" (
  "knowledgePointId" TEXT NOT NULL,
  "unitNumber" INTEGER NOT NULL,
  "officialTitle" TEXT NOT NULL,
  CONSTRAINT "GrammarKnowledgePointUnit_pkey" PRIMARY KEY ("knowledgePointId", "unitNumber")
);

CREATE INDEX "GrammarBookEdition_sortOrder_idx" ON "GrammarBookEdition"("sortOrder");
CREATE UNIQUE INDEX "GrammarSection_bookEditionId_sortOrder_key" ON "GrammarSection"("bookEditionId", "sortOrder");
CREATE INDEX "GrammarSection_bookEditionId_sortOrder_idx" ON "GrammarSection"("bookEditionId", "sortOrder");
CREATE INDEX "KnowledgePoint_source_bookEditionId_sortOrder_idx" ON "KnowledgePoint"("source", "bookEditionId", "sortOrder");
CREATE INDEX "KnowledgePoint_sectionId_sortOrder_idx" ON "KnowledgePoint"("sectionId", "sortOrder");
CREATE INDEX "GrammarKnowledgePointUnit_unitNumber_idx" ON "GrammarKnowledgePointUnit"("unitNumber");

ALTER TABLE "Course" ADD CONSTRAINT "Course_grammarBookEditionId_fkey" FOREIGN KEY ("grammarBookEditionId") REFERENCES "GrammarBookEdition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GrammarSection" ADD CONSTRAINT "GrammarSection_bookEditionId_fkey" FOREIGN KEY ("bookEditionId") REFERENCES "GrammarBookEdition"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KnowledgePoint" ADD CONSTRAINT "KnowledgePoint_bookEditionId_fkey" FOREIGN KEY ("bookEditionId") REFERENCES "GrammarBookEdition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "KnowledgePoint" ADD CONSTRAINT "KnowledgePoint_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "GrammarSection"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GrammarKnowledgePointUnit" ADD CONSTRAINT "GrammarKnowledgePointUnit_knowledgePointId_fkey" FOREIGN KEY ("knowledgePointId") REFERENCES "KnowledgePoint"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "KnowledgePoint" ("id", "source", "bookEditionId", "sectionId", "title", "sortOrder")
SELECT "id", 'legacy'::"KnowledgePointSource", NULL, NULL, "label", "sortOrder"
FROM "PresetOption"
WHERE "kind" = 'grammar'::"PresetOptionKind"
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "GrammarBookEdition" ("id", "title", "edition", "officialLevel", "sortOrder") VALUES
  ('essential-grammar-in-use-4', 'Essential Grammar in Use', 'Fourth Edition', 'A1–B1', 1),
  ('english-grammar-in-use-5', 'English Grammar in Use', 'Fifth Edition', 'B1–B2', 2),
  ('advanced-grammar-in-use-4', 'Advanced Grammar in Use', 'Fourth Edition', 'C1–C2', 3);

INSERT INTO "GrammarSection" ("id", "bookEditionId", "officialTitle", "sortOrder") VALUES
  ('essential-grammar-in-use-4-s1', 'essential-grammar-in-use-4', 'Present', 1),
  ('essential-grammar-in-use-4-s2', 'essential-grammar-in-use-4', 'Past', 2),
  ('essential-grammar-in-use-4-s3', 'essential-grammar-in-use-4', 'Present perfect', 3),
  ('essential-grammar-in-use-4-s4', 'essential-grammar-in-use-4', 'Passive', 4),
  ('essential-grammar-in-use-4-s5', 'essential-grammar-in-use-4', 'Verb forms', 5),
  ('essential-grammar-in-use-4-s6', 'essential-grammar-in-use-4', 'Future', 6),
  ('essential-grammar-in-use-4-s7', 'essential-grammar-in-use-4', 'Modals, imperative etc.', 7),
  ('essential-grammar-in-use-4-s8', 'essential-grammar-in-use-4', 'There and it', 8),
  ('essential-grammar-in-use-4-s9', 'essential-grammar-in-use-4', 'Auxiliary verbs', 9),
  ('essential-grammar-in-use-4-s10', 'essential-grammar-in-use-4', 'Questions', 10),
  ('essential-grammar-in-use-4-s11', 'essential-grammar-in-use-4', 'Reported speech', 11),
  ('essential-grammar-in-use-4-s12', 'essential-grammar-in-use-4', '-ing and to ...', 12),
  ('essential-grammar-in-use-4-s13', 'essential-grammar-in-use-4', 'Go, get, do, make and have', 13),
  ('essential-grammar-in-use-4-s14', 'essential-grammar-in-use-4', 'Pronouns and possessives', 14),
  ('essential-grammar-in-use-4-s15', 'essential-grammar-in-use-4', 'A and the', 15),
  ('essential-grammar-in-use-4-s16', 'essential-grammar-in-use-4', 'Determiners and pronouns', 16),
  ('essential-grammar-in-use-4-s17', 'essential-grammar-in-use-4', 'Adjectives and adverbs', 17),
  ('essential-grammar-in-use-4-s18', 'essential-grammar-in-use-4', 'Word order', 18),
  ('essential-grammar-in-use-4-s19', 'essential-grammar-in-use-4', 'Conjunctions and clauses', 19),
  ('essential-grammar-in-use-4-s20', 'essential-grammar-in-use-4', 'Prepositions', 20),
  ('essential-grammar-in-use-4-s21', 'essential-grammar-in-use-4', 'Phrasal verbs', 21),
  ('english-grammar-in-use-5-s1', 'english-grammar-in-use-5', 'Present and past', 1),
  ('english-grammar-in-use-5-s2', 'english-grammar-in-use-5', 'Present perfect and past', 2),
  ('english-grammar-in-use-5-s3', 'english-grammar-in-use-5', 'Future', 3),
  ('english-grammar-in-use-5-s4', 'english-grammar-in-use-5', 'Modals', 4),
  ('english-grammar-in-use-5-s5', 'english-grammar-in-use-5', 'if and wish', 5),
  ('english-grammar-in-use-5-s6', 'english-grammar-in-use-5', 'Passive', 6),
  ('english-grammar-in-use-5-s7', 'english-grammar-in-use-5', 'Reported speech', 7),
  ('english-grammar-in-use-5-s8', 'english-grammar-in-use-5', 'Questions and auxiliary verbs', 8),
  ('english-grammar-in-use-5-s9', 'english-grammar-in-use-5', '-ing and to ...', 9),
  ('english-grammar-in-use-5-s10', 'english-grammar-in-use-5', 'Articles and nouns', 10),
  ('english-grammar-in-use-5-s11', 'english-grammar-in-use-5', 'Pronouns and determiners', 11),
  ('english-grammar-in-use-5-s12', 'english-grammar-in-use-5', 'Relative clauses', 12),
  ('english-grammar-in-use-5-s13', 'english-grammar-in-use-5', 'Adjectives and adverbs', 13),
  ('english-grammar-in-use-5-s14', 'english-grammar-in-use-5', 'Conjunctions and prepositions', 14),
  ('english-grammar-in-use-5-s15', 'english-grammar-in-use-5', 'Prepositions', 15),
  ('english-grammar-in-use-5-s16', 'english-grammar-in-use-5', 'Phrasal verbs', 16),
  ('advanced-grammar-in-use-4-s1', 'advanced-grammar-in-use-4', 'Tenses', 1),
  ('advanced-grammar-in-use-4-s2', 'advanced-grammar-in-use-4', 'The future', 2),
  ('advanced-grammar-in-use-4-s3', 'advanced-grammar-in-use-4', 'Modals and semi-modals', 3),
  ('advanced-grammar-in-use-4-s4', 'advanced-grammar-in-use-4', 'Linking verbs, passives, questions', 4),
  ('advanced-grammar-in-use-4-s5', 'advanced-grammar-in-use-4', 'Verb complementation: what follows verbs', 5),
  ('advanced-grammar-in-use-4-s6', 'advanced-grammar-in-use-4', 'Reporting', 6),
  ('advanced-grammar-in-use-4-s7', 'advanced-grammar-in-use-4', 'Nouns', 7),
  ('advanced-grammar-in-use-4-s8', 'advanced-grammar-in-use-4', 'Articles, determiners and quantifiers', 8),
  ('advanced-grammar-in-use-4-s9', 'advanced-grammar-in-use-4', 'Relative clauses and other types of clause', 9),
  ('advanced-grammar-in-use-4-s10', 'advanced-grammar-in-use-4', 'Pronouns, substitution and leaving out words', 10),
  ('advanced-grammar-in-use-4-s11', 'advanced-grammar-in-use-4', 'Adjectives and adverbs', 11),
  ('advanced-grammar-in-use-4-s12', 'advanced-grammar-in-use-4', 'Adverbial clauses and conjunctions', 12),
  ('advanced-grammar-in-use-4-s13', 'advanced-grammar-in-use-4', 'Prepositions', 13),
  ('advanced-grammar-in-use-4-s14', 'advanced-grammar-in-use-4', 'Organising information', 14),
  ('advanced-grammar-in-use-4-s15', 'advanced-grammar-in-use-4', 'Grammar in academic contexts', 15);

INSERT INTO "KnowledgePoint" ("id", "source", "bookEditionId", "sectionId", "title", "sortOrder") VALUES
  ('essential-grammar-in-use-4-u1', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'am/is/are', 1),
  ('essential-grammar-in-use-4-u2', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'am/is/are (questions)', 2),
  ('essential-grammar-in-use-4-u3', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'I am doing (present continuous)', 3),
  ('essential-grammar-in-use-4-u4', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'are you doing? (present continuous questions)', 4),
  ('essential-grammar-in-use-4-u5', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'I do/work/like etc. (present simple)', 5),
  ('essential-grammar-in-use-4-u6', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'I don’t ... (present simple negative)', 6),
  ('essential-grammar-in-use-4-u7', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'Do you ... ? (present simple questions)', 7),
  ('essential-grammar-in-use-4-u8', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'I am doing (present continuous) and I do (present simple)', 8),
  ('essential-grammar-in-use-4-u9', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s1', 'I have ... and I’ve got ...', 9),
  ('essential-grammar-in-use-4-u10', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s2', 'was/were', 10),
  ('essential-grammar-in-use-4-u11', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s2', 'worked/got/went etc. (past simple)', 11),
  ('essential-grammar-in-use-4-u12', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s2', 'I didn’t ... Did you ... ? (past simple negative and questions)', 12),
  ('essential-grammar-in-use-4-u13', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s2', 'I was doing (past continuous)', 13),
  ('essential-grammar-in-use-4-u14', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s2', 'I was doing (past continuous) and I did (past simple)', 14),
  ('essential-grammar-in-use-4-u15', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'I have done (present perfect 1)', 15),
  ('essential-grammar-in-use-4-u16', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'I’ve just ... I’ve already ... I haven’t ... yet (present perfect 2)', 16),
  ('essential-grammar-in-use-4-u17', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'Have you ever ... ? (present perfect 3)', 17),
  ('essential-grammar-in-use-4-u18', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'How long have you ... ? (present perfect 4)', 18),
  ('essential-grammar-in-use-4-u19', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'for since ago', 19),
  ('essential-grammar-in-use-4-u20', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s3', 'I have done (present perfect) and I did (past)', 20),
  ('essential-grammar-in-use-4-u21', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s4', 'is done was done (passive 1)', 21),
  ('essential-grammar-in-use-4-u22', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s4', 'is being done has been done (passive 2)', 22),
  ('essential-grammar-in-use-4-u23', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s5', 'be/have/do in present and past tenses', 23),
  ('essential-grammar-in-use-4-u24', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s5', 'Regular and irregular verbs', 24),
  ('essential-grammar-in-use-4-u25', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s6', 'What are you doing tomorrow?', 25),
  ('essential-grammar-in-use-4-u26', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s6', 'I’m going to ...', 26),
  ('essential-grammar-in-use-4-u27-28', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s6', 'will/shall', 27),
  ('essential-grammar-in-use-4-u29', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'might', 29),
  ('essential-grammar-in-use-4-u30', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'can and could', 30),
  ('essential-grammar-in-use-4-u31', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'must mustn’t don’t need to', 31),
  ('essential-grammar-in-use-4-u32', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'should', 32),
  ('essential-grammar-in-use-4-u33', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'I have to ...', 33),
  ('essential-grammar-in-use-4-u34', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'Would you like ... ? I’d like ...', 34),
  ('essential-grammar-in-use-4-u35', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'Do this! Don’t do that! Let’s do this!', 35),
  ('essential-grammar-in-use-4-u36', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s7', 'I used to ...', 36),
  ('essential-grammar-in-use-4-u37', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s8', 'there is there are', 37),
  ('essential-grammar-in-use-4-u38', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s8', 'there was/were there has/have been there will be', 38),
  ('essential-grammar-in-use-4-u39', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s8', 'It ...', 39),
  ('essential-grammar-in-use-4-u40', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s9', 'I am, I don’t etc.', 40),
  ('essential-grammar-in-use-4-u41', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s9', 'Have you? Are you? Don’t you? etc.', 41),
  ('essential-grammar-in-use-4-u42', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s9', 'too/either so am I / neither do I etc.', 42),
  ('essential-grammar-in-use-4-u43', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s9', 'isn’t, haven’t, don’t etc. (negatives)', 43),
  ('essential-grammar-in-use-4-u44', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'is it ... ? have you ... ? do they ... ? etc. (questions 1)', 44),
  ('essential-grammar-in-use-4-u45', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'Who saw you? Who did you see? (questions 2)', 45),
  ('essential-grammar-in-use-4-u46', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'Who is she talking to? What is it like? (questions 3)', 46),
  ('essential-grammar-in-use-4-u47', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'What ... ? Which ... ? How ... ? (questions 4)', 47),
  ('essential-grammar-in-use-4-u48', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'How long does it take ... ?', 48),
  ('essential-grammar-in-use-4-u49', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s10', 'Do you know where ... ? I don’t know what ... etc.', 49),
  ('essential-grammar-in-use-4-u50', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s11', 'She said that ... He told me that ...', 50),
  ('essential-grammar-in-use-4-u51', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s12', 'work/working go/going do/doing', 51),
  ('essential-grammar-in-use-4-u52', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s12', 'to ... (I want to do) and -ing (I enjoy doing)', 52),
  ('essential-grammar-in-use-4-u53', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s12', 'I want you to ... I told you to ...', 53),
  ('essential-grammar-in-use-4-u54', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s12', 'I went to the shop to ...', 54),
  ('essential-grammar-in-use-4-u55', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s13', 'go to ... go on ... go for ... go -ing', 55),
  ('essential-grammar-in-use-4-u56', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s13', 'get', 56),
  ('essential-grammar-in-use-4-u57', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s13', 'do and make', 57),
  ('essential-grammar-in-use-4-u58', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s13', 'have', 58),
  ('essential-grammar-in-use-4-u59', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', 'I/me he/him they/them etc.', 59),
  ('essential-grammar-in-use-4-u60', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', 'my/his/their etc.', 60),
  ('essential-grammar-in-use-4-u61', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', 'Whose is this? It’s mine/yours/hers etc.', 61),
  ('essential-grammar-in-use-4-u62', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', 'I/me/my/mine', 62),
  ('essential-grammar-in-use-4-u63', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', 'myself/yourself/themselves etc.', 63),
  ('essential-grammar-in-use-4-u64', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s14', '-’s (Kate’s camera / my brother’s car etc.)', 64),
  ('essential-grammar-in-use-4-u65', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'a/an ...', 65),
  ('essential-grammar-in-use-4-u66', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'train(s) bus(es) (singular and plural)', 66),
  ('essential-grammar-in-use-4-u67', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'a bottle / some water (countable/uncountable 1)', 67),
  ('essential-grammar-in-use-4-u68', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'a cake / some cake / some cakes (countable/uncountable 2)', 68),
  ('essential-grammar-in-use-4-u69', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'a/an and the', 69),
  ('essential-grammar-in-use-4-u70', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'the ...', 70),
  ('essential-grammar-in-use-4-u71', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'go to work go home go to the cinema', 71),
  ('essential-grammar-in-use-4-u72', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'I like music I hate exams', 72),
  ('essential-grammar-in-use-4-u73', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s15', 'the ... (names of places)', 73),
  ('essential-grammar-in-use-4-u74', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'this/that/these/those', 74),
  ('essential-grammar-in-use-4-u75', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'one/ones', 75),
  ('essential-grammar-in-use-4-u76', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'some and any', 76),
  ('essential-grammar-in-use-4-u77', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'not + any no none', 77),
  ('essential-grammar-in-use-4-u78', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'not + anybody/anyone/anything nobody/no-one/nothing', 78),
  ('essential-grammar-in-use-4-u79', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'somebody/anything/nowhere etc.', 79),
  ('essential-grammar-in-use-4-u80', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'every and all', 80),
  ('essential-grammar-in-use-4-u81', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'all most some any no/none', 81),
  ('essential-grammar-in-use-4-u82', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'both either neither', 82),
  ('essential-grammar-in-use-4-u83', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', 'a lot much many', 83),
  ('essential-grammar-in-use-4-u84', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s16', '(a) little (a) few', 84),
  ('essential-grammar-in-use-4-u85', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'old/nice/interesting etc. (adjectives)', 85),
  ('essential-grammar-in-use-4-u86', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'quickly/badly/suddenly etc. (adverbs)', 86),
  ('essential-grammar-in-use-4-u87', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'old/older expensive / more expensive', 87),
  ('essential-grammar-in-use-4-u88', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'older than ... more expensive than ...', 88),
  ('essential-grammar-in-use-4-u89', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'not as ... as', 89),
  ('essential-grammar-in-use-4-u90', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'the oldest the most expensive', 90),
  ('essential-grammar-in-use-4-u91', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'enough', 91),
  ('essential-grammar-in-use-4-u92', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s17', 'too', 92),
  ('essential-grammar-in-use-4-u93', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s18', 'He speaks English very well. (word order 1)', 93),
  ('essential-grammar-in-use-4-u94', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s18', 'always/usually/often etc. (word order 2)', 94),
  ('essential-grammar-in-use-4-u95', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s18', 'still yet already', 95),
  ('essential-grammar-in-use-4-u96', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s18', 'Give me that book! Give it to me!', 96),
  ('essential-grammar-in-use-4-u97', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'and but or so because', 97),
  ('essential-grammar-in-use-4-u98', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'When ...', 98),
  ('essential-grammar-in-use-4-u99', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'If we go ... If you see ... etc.', 99),
  ('essential-grammar-in-use-4-u100', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'If I had ... If we went ... etc.', 100),
  ('essential-grammar-in-use-4-u101', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'a person who ... a thing that/which ... (relative clauses 1)', 101),
  ('essential-grammar-in-use-4-u102', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s19', 'the people we met the hotel you stayed at (relative clauses 2)', 102),
  ('essential-grammar-in-use-4-u103', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'at 8 o’clock on Monday in April', 103),
  ('essential-grammar-in-use-4-u104', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'from ... to until since for', 104),
  ('essential-grammar-in-use-4-u105', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'before after during while', 105),
  ('essential-grammar-in-use-4-u106', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'in at on (places 1)', 106),
  ('essential-grammar-in-use-4-u107', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'in at on (places 2)', 107),
  ('essential-grammar-in-use-4-u108', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'to in at (places 3)', 108),
  ('essential-grammar-in-use-4-u109', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'under, behind, opposite etc.', 109),
  ('essential-grammar-in-use-4-u110', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'up, over, through etc.', 110),
  ('essential-grammar-in-use-4-u111', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'on at by with about', 111),
  ('essential-grammar-in-use-4-u112', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'afraid of ..., good at ... etc. of/at/for etc. (prepositions) + -ing', 112),
  ('essential-grammar-in-use-4-u113', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s20', 'listen to ..., look at ... etc. (verb + preposition)', 113),
  ('essential-grammar-in-use-4-u114', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s21', 'go in, fall off, run away etc. (phrasal verbs 1)', 114),
  ('essential-grammar-in-use-4-u115', 'grammar_in_use', 'essential-grammar-in-use-4', 'essential-grammar-in-use-4-s21', 'put on your shoes put your shoes on (phrasal verbs 2)', 115),
  ('english-grammar-in-use-5-u1', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s1', 'Present continuous (I am doing)', 1),
  ('english-grammar-in-use-5-u2', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s1', 'Present simple (I do)', 2),
  ('english-grammar-in-use-5-u3-4', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s1', 'Present continuous and present simple', 3),
  ('english-grammar-in-use-5-u5', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s1', 'Past simple (I did)', 5),
  ('english-grammar-in-use-5-u6', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s1', 'Past continuous (I was doing)', 6),
  ('english-grammar-in-use-5-u7-8', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Present perfect', 7),
  ('english-grammar-in-use-5-u9', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Present perfect continuous (I have been doing)', 9),
  ('english-grammar-in-use-5-u10', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Present perfect continuous and simple (I have been doing and I have done)', 10),
  ('english-grammar-in-use-5-u11', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'how long have you (been) ... ?', 11),
  ('english-grammar-in-use-5-u12', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'for and since when ... ? and how long ... ?', 12),
  ('english-grammar-in-use-5-u13-14', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Present perfect and past', 13),
  ('english-grammar-in-use-5-u15', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Past perfect (I had done)', 15),
  ('english-grammar-in-use-5-u16', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'Past perfect continuous (I had been doing)', 16),
  ('english-grammar-in-use-5-u17', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'have and have got', 17),
  ('english-grammar-in-use-5-u18', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s2', 'used to (do)', 18),
  ('english-grammar-in-use-5-u19', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'Present tenses (I am doing / I do) for the future', 19),
  ('english-grammar-in-use-5-u20', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'I’m going to (do)', 20),
  ('english-grammar-in-use-5-u21-22', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'will and shall', 21),
  ('english-grammar-in-use-5-u23', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'I will and I’m going to', 23),
  ('english-grammar-in-use-5-u24', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'will be doing and will have done', 24),
  ('english-grammar-in-use-5-u25', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s3', 'when I do and when I’ve done if and when', 25),
  ('english-grammar-in-use-5-u26', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'can, could and (be) able to', 26),
  ('english-grammar-in-use-5-u27', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'could (do) and could have (done)', 27),
  ('english-grammar-in-use-5-u28', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'must and can’t', 28),
  ('english-grammar-in-use-5-u29-30', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'may and might', 29),
  ('english-grammar-in-use-5-u31', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'have to and must', 31),
  ('english-grammar-in-use-5-u32', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'must mustn’t needn’t', 32),
  ('english-grammar-in-use-5-u33-34', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'should', 33),
  ('english-grammar-in-use-5-u35', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', '’d better ... it’s time ...', 35),
  ('english-grammar-in-use-5-u36', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'would', 36),
  ('english-grammar-in-use-5-u37', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s4', 'can/could/would you ... ? etc. (Requests, offers, permission and invitations)', 37),
  ('english-grammar-in-use-5-u38', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s5', 'if I do ... and if I did ...', 38),
  ('english-grammar-in-use-5-u39', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s5', 'if I knew ... I wish I knew ...', 39),
  ('english-grammar-in-use-5-u40', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s5', 'if I had known ... I wish I had known ...', 40),
  ('english-grammar-in-use-5-u41', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s5', 'wish', 41),
  ('english-grammar-in-use-5-u42', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s6', 'Passive 1 (is done / was done)', 42),
  ('english-grammar-in-use-5-u43', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s6', 'Passive 2 (be done / been done / being done)', 43),
  ('english-grammar-in-use-5-u44', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s6', 'Passive 3', 44),
  ('english-grammar-in-use-5-u45', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s6', 'it is said that ... he is said to ... he is supposed to ...', 45),
  ('english-grammar-in-use-5-u46', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s6', 'have something done', 46),
  ('english-grammar-in-use-5-u47', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s7', 'Reported speech 1 (he said that ...)', 47),
  ('english-grammar-in-use-5-u48', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s7', 'Reported speech 2', 48),
  ('english-grammar-in-use-5-u49', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s8', 'Questions 1', 49),
  ('english-grammar-in-use-5-u50', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s8', 'Questions 2 (do you know where ... ? / he asked me where ...)', 50),
  ('english-grammar-in-use-5-u51', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s8', 'Auxiliary verbs (have/do/can etc.) I think so / I hope so etc.', 51),
  ('english-grammar-in-use-5-u52', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s8', 'Question tags (do you? isn’t it? etc.)', 52),
  ('english-grammar-in-use-5-u53', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + -ing (enjoy doing / stop doing etc.)', 53),
  ('english-grammar-in-use-5-u54', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + to ... (decide to ... / forget to ... etc.)', 54),
  ('english-grammar-in-use-5-u55', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb (+ object) + to ... (I want you to ...)', 55),
  ('english-grammar-in-use-5-u56', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + -ing or to ... 1 (remember, regret etc.)', 56),
  ('english-grammar-in-use-5-u57', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + -ing or to ... 2 (try, need, help)', 57),
  ('english-grammar-in-use-5-u58', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + -ing or to ... 3 (like / would like etc.)', 58),
  ('english-grammar-in-use-5-u59', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'prefer and would rather', 59),
  ('english-grammar-in-use-5-u60', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Preposition (in/for/about etc.) + -ing', 60),
  ('english-grammar-in-use-5-u61', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'be/get used to ... (I’m used to ...)', 61),
  ('english-grammar-in-use-5-u62', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Verb + preposition + -ing (succeed in -ing / insist on -ing etc.)', 62),
  ('english-grammar-in-use-5-u63', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'there’s no point in -ing, it’s worth -ing etc.', 63),
  ('english-grammar-in-use-5-u64', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'to ..., for ... and so that ...', 64),
  ('english-grammar-in-use-5-u65', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'Adjective + to ...', 65),
  ('english-grammar-in-use-5-u66', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'to ... (afraid to do) and preposition + -ing (afraid of -ing)', 66),
  ('english-grammar-in-use-5-u67', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', 'see somebody do and see somebody doing', 67),
  ('english-grammar-in-use-5-u68', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s9', '-ing clauses (He hurt his knee playing football.)', 68),
  ('english-grammar-in-use-5-u69-70', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'Countable and uncountable', 69),
  ('english-grammar-in-use-5-u71', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'Countable nouns with a/an and some', 71),
  ('english-grammar-in-use-5-u72', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'a/an and the', 72),
  ('english-grammar-in-use-5-u73', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'the 1', 73),
  ('english-grammar-in-use-5-u74', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'the 2 (school / the school etc.)', 74),
  ('english-grammar-in-use-5-u75', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'the 3 (children / the children)', 75),
  ('english-grammar-in-use-5-u76', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'the 4 (the giraffe / the telephone / the old etc.)', 76),
  ('english-grammar-in-use-5-u77-78', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'Names with and without the', 77),
  ('english-grammar-in-use-5-u79', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'Singular and plural', 79),
  ('english-grammar-in-use-5-u80', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', 'Noun + noun (a bus driver / a headache)', 80),
  ('english-grammar-in-use-5-u81', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s10', '-’s (your sister’s name) and of ... (the name of the book)', 81),
  ('english-grammar-in-use-5-u82', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'myself/yourself/themselves etc.', 82),
  ('english-grammar-in-use-5-u83', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'a friend of mine my own house on my own/by myself', 83),
  ('english-grammar-in-use-5-u84', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'there ... and it ...', 84),
  ('english-grammar-in-use-5-u85', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'some and any', 85),
  ('english-grammar-in-use-5-u86', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'no/none/any nothing/nobody etc.', 86),
  ('english-grammar-in-use-5-u87', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'much, many, little, few, a lot, plenty', 87),
  ('english-grammar-in-use-5-u88', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'all/all of most/most of no/none of etc.', 88),
  ('english-grammar-in-use-5-u89', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'both/both of neither/neither of either/either of', 89),
  ('english-grammar-in-use-5-u90', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'all every whole', 90),
  ('english-grammar-in-use-5-u91', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s11', 'each and every', 91),
  ('english-grammar-in-use-5-u92', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', 'Relative clauses 1: clauses with who/that/which', 92),
  ('english-grammar-in-use-5-u93', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', 'Relative clauses 2: clauses with and without who/that/which', 93),
  ('english-grammar-in-use-5-u94', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', 'Relative clauses 3: whose/whom/where', 94),
  ('english-grammar-in-use-5-u95', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', 'Relative clauses 4: extra information clauses (1)', 95),
  ('english-grammar-in-use-5-u96', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', 'Relative clauses 5: extra information clauses (2)', 96),
  ('english-grammar-in-use-5-u97', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s12', '-ing and -ed clauses (the woman talking to Tom, the boy injured in the accident)', 97),
  ('english-grammar-in-use-5-u98', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Adjectives ending in -ing and -ed (boring/bored etc.)', 98),
  ('english-grammar-in-use-5-u99', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Adjectives: a nice new house, you look tired', 99),
  ('english-grammar-in-use-5-u100', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Adjectives and adverbs 1 (quick/quickly)', 100),
  ('english-grammar-in-use-5-u101', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Adjectives and adverbs 2 (well, fast, late, hard/hardly)', 101),
  ('english-grammar-in-use-5-u102', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'so and such', 102),
  ('english-grammar-in-use-5-u103', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'enough and too', 103),
  ('english-grammar-in-use-5-u104', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'quite, pretty, rather and fairly', 104),
  ('english-grammar-in-use-5-u105', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Comparative 1 (cheaper, more expensive etc.)', 105),
  ('english-grammar-in-use-5-u106', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Comparative 2 (much better / any better etc.)', 106),
  ('english-grammar-in-use-5-u107', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Comparative 3 (as ... as / than)', 107),
  ('english-grammar-in-use-5-u108', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Superlative (the longest, the most enjoyable etc.)', 108),
  ('english-grammar-in-use-5-u109', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Word order 1: verb + object; place and time', 109),
  ('english-grammar-in-use-5-u110', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'Word order 2: adverbs with the verb', 110),
  ('english-grammar-in-use-5-u111', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'still anymore yet already', 111),
  ('english-grammar-in-use-5-u112', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s13', 'even', 112),
  ('english-grammar-in-use-5-u113', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'although though even though in spite of despite', 113),
  ('english-grammar-in-use-5-u114', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'in case', 114),
  ('english-grammar-in-use-5-u115', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'unless as long as provided', 115),
  ('english-grammar-in-use-5-u116', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'as (as I walked ... / as I was ... etc.)', 116),
  ('english-grammar-in-use-5-u117', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'like and as', 117),
  ('english-grammar-in-use-5-u118', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'like as if', 118),
  ('english-grammar-in-use-5-u119', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'during for while', 119),
  ('english-grammar-in-use-5-u120', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s14', 'by and until by the time ...', 120),
  ('english-grammar-in-use-5-u121', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'at/on/in (time)', 121),
  ('english-grammar-in-use-5-u122', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'on time and in time at the end and in the end', 122),
  ('english-grammar-in-use-5-u123-125', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'in/at/on (position)', 123),
  ('english-grammar-in-use-5-u126', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'to, at, in and into', 126),
  ('english-grammar-in-use-5-u127', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'in/on/at (other uses)', 127),
  ('english-grammar-in-use-5-u128', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'by', 128),
  ('english-grammar-in-use-5-u129', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Noun + preposition (reason for, cause of etc.)', 129),
  ('english-grammar-in-use-5-u130-131', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Adjective + preposition', 130),
  ('english-grammar-in-use-5-u132', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Verb + preposition 1 to and at', 132),
  ('english-grammar-in-use-5-u133', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Verb + preposition 2 about/for/of/after', 133),
  ('english-grammar-in-use-5-u134', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Verb + preposition 3 about and of', 134),
  ('english-grammar-in-use-5-u135', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Verb + preposition 4 of/for/from/on', 135),
  ('english-grammar-in-use-5-u136', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s15', 'Verb + preposition 5 in/into/with/to/on', 136),
  ('english-grammar-in-use-5-u137', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 1 Introduction', 137),
  ('english-grammar-in-use-5-u138', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 2 in/out', 138),
  ('english-grammar-in-use-5-u139', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 3 out', 139),
  ('english-grammar-in-use-5-u140', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 4 on/off (1)', 140),
  ('english-grammar-in-use-5-u141', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 5 on/off (2)', 141),
  ('english-grammar-in-use-5-u142', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 6 up/down', 142),
  ('english-grammar-in-use-5-u143', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 7 up (1)', 143),
  ('english-grammar-in-use-5-u144', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 8 up (2)', 144),
  ('english-grammar-in-use-5-u145', 'grammar_in_use', 'english-grammar-in-use-5', 'english-grammar-in-use-5-s16', 'Phrasal verbs 9 away/back', 145),
  ('advanced-grammar-in-use-4-u1', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Present continuous and present simple: state verbs and performatives', 1),
  ('advanced-grammar-in-use-4-u2', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Using present continuous and present simple', 2),
  ('advanced-grammar-in-use-4-u3', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Past simple and present perfect', 3),
  ('advanced-grammar-in-use-4-u4', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Past continuous and past simple', 4),
  ('advanced-grammar-in-use-4-u5', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Past perfect and past simple', 5),
  ('advanced-grammar-in-use-4-u6', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Present perfect continuous and present perfect', 6),
  ('advanced-grammar-in-use-4-u7', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Past perfect continuous, past perfect and past continuous', 7),
  ('advanced-grammar-in-use-4-u8', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s1', 'Present and past time: review', 8),
  ('advanced-grammar-in-use-4-u9', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'Will and be going to', 9),
  ('advanced-grammar-in-use-4-u10', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'Present simple and present continuous for the future', 10),
  ('advanced-grammar-in-use-4-u11', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'Future continuous, future perfect and future perfect continuous', 11),
  ('advanced-grammar-in-use-4-u12', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'Be to + infinitive; be about to + infinitive', 12),
  ('advanced-grammar-in-use-4-u13', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'Other ways of talking about the future', 13),
  ('advanced-grammar-in-use-4-u14', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s2', 'The future seen from the past', 14),
  ('advanced-grammar-in-use-4-u15', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'Can, could, be able to and be allowed to', 15),
  ('advanced-grammar-in-use-4-u16', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'Will, would and used to', 16),
  ('advanced-grammar-in-use-4-u17', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'May and might', 17),
  ('advanced-grammar-in-use-4-u18', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'Must and have (got) to', 18),
  ('advanced-grammar-in-use-4-u19', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'Need(n’t), don’t need to and don’t have to', 19),
  ('advanced-grammar-in-use-4-u20', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s3', 'Should, ought to and had better', 20),
  ('advanced-grammar-in-use-4-u21', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Linking verbs: be, appear, seem; become, get, etc.', 21),
  ('advanced-grammar-in-use-4-u22', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Using passives', 22),
  ('advanced-grammar-in-use-4-u23', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Forming passive sentences: objects, complements and multi-word verbs', 23),
  ('advanced-grammar-in-use-4-u24', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Forming passive sentences: verb + -ing or to-infinitive', 24),
  ('advanced-grammar-in-use-4-u25', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Reporting with passives; It is said that ...', 25),
  ('advanced-grammar-in-use-4-u26', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Wh-questions with who, whom, which, how and whose', 26),
  ('advanced-grammar-in-use-4-u27', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s4', 'Negative questions; echo questions; questions with that-clauses', 27),
  ('advanced-grammar-in-use-4-u28', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s5', 'Verbs, objects and complements', 28),
  ('advanced-grammar-in-use-4-u29', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s5', 'Verb + two objects', 29),
  ('advanced-grammar-in-use-4-u30-31', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s5', 'Verb + -ing forms and infinitives', 30),
  ('advanced-grammar-in-use-4-u32', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Reporting people’s words and thoughts', 32),
  ('advanced-grammar-in-use-4-u33', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Reporting statements: that-clauses', 33),
  ('advanced-grammar-in-use-4-u34', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Verb + wh-clause', 34),
  ('advanced-grammar-in-use-4-u35', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Tense choice in reporting', 35),
  ('advanced-grammar-in-use-4-u36', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Reporting offers, suggestions, orders, intentions, etc.', 36),
  ('advanced-grammar-in-use-4-u37', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Modal verbs in reporting', 37),
  ('advanced-grammar-in-use-4-u38', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Reporting what people say using nouns and adjectives', 38),
  ('advanced-grammar-in-use-4-u39', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s6', 'Should in that-clauses; the present subjunctive', 39),
  ('advanced-grammar-in-use-4-u40-42', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s7', 'Agreement between subject and verb', 40),
  ('advanced-grammar-in-use-4-u43', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s7', 'Compound nouns and noun phrases', 43),
  ('advanced-grammar-in-use-4-u44', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'A/an and one', 44),
  ('advanced-grammar-in-use-4-u45-47', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'A/an, the and zero article', 45),
  ('advanced-grammar-in-use-4-u48', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'Some and any', 48),
  ('advanced-grammar-in-use-4-u49', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'No, none (of) and not any', 49),
  ('advanced-grammar-in-use-4-u50', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'Much (of), many (of), a lot of, lots (of), etc.', 50),
  ('advanced-grammar-in-use-4-u51', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'All (of), whole, every, each', 51),
  ('advanced-grammar-in-use-4-u52', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s8', 'Few, little, less, fewer', 52),
  ('advanced-grammar-in-use-4-u53', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Relative pronouns', 53),
  ('advanced-grammar-in-use-4-u54', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Other relative words: whose, when, whereby, etc.', 54),
  ('advanced-grammar-in-use-4-u55', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Prepositions in relative clauses', 55),
  ('advanced-grammar-in-use-4-u56', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Other ways of adding information to noun phrases 1: additional noun phrases, etc.', 56),
  ('advanced-grammar-in-use-4-u57', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Other ways of adding information to noun phrases 2: prepositional phrases, etc.', 57),
  ('advanced-grammar-in-use-4-u58-59', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s9', 'Participle clauses with adverbial meaning', 58),
  ('advanced-grammar-in-use-4-u60', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'Reflexive pronouns: herself, himself, themselves, etc.', 60),
  ('advanced-grammar-in-use-4-u61', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'One and ones', 61),
  ('advanced-grammar-in-use-4-u62', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'So and not as substitutes for clauses, etc.', 62),
  ('advanced-grammar-in-use-4-u63', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'Do so; such', 63),
  ('advanced-grammar-in-use-4-u64', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'More on ellipsis after auxiliary verbs', 64),
  ('advanced-grammar-in-use-4-u65', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s10', 'Ellipsis of to-infinitives', 65),
  ('advanced-grammar-in-use-4-u66', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Position of adjectives', 66),
  ('advanced-grammar-in-use-4-u67', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Gradable and non-gradable adjectives: using adjectives with adverbs', 67),
  ('advanced-grammar-in-use-4-u68', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Gradable and non-gradable adjectives: differences in meaning', 68),
  ('advanced-grammar-in-use-4-u69', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Participle adjectives and compound adjectives', 69),
  ('advanced-grammar-in-use-4-u70', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Adjectives + to-infinitive, -ing, that-clause, wh-clause', 70),
  ('advanced-grammar-in-use-4-u71', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Adjectives and adverbs', 71),
  ('advanced-grammar-in-use-4-u72', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Adjectives and adverbs: comparative and superlative forms', 72),
  ('advanced-grammar-in-use-4-u73', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Comparative phrases and clauses', 73),
  ('advanced-grammar-in-use-4-u74', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Position of adverbs: end position', 74),
  ('advanced-grammar-in-use-4-u75', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Position of adverbs: front and mid position', 75),
  ('advanced-grammar-in-use-4-u76', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Adverbs of place, direction, indefinite frequency, and time', 76),
  ('advanced-grammar-in-use-4-u77', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Degree adverbs and focus adverbs', 77),
  ('advanced-grammar-in-use-4-u78', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s11', 'Comment adverbs and viewpoint adverbs', 78),
  ('advanced-grammar-in-use-4-u79', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'Adverbial clauses of time', 79),
  ('advanced-grammar-in-use-4-u80', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'Giving reasons: as, because, etc.; for and with', 80),
  ('advanced-grammar-in-use-4-u81', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'Purposes and results: in order to, so as to, etc.', 81),
  ('advanced-grammar-in-use-4-u82', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'Contrasts: although and though; even though / if; while, whilst and whereas', 82),
  ('advanced-grammar-in-use-4-u83', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'If: real and unreal conditionals', 83),
  ('advanced-grammar-in-use-4-u84', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'If: other conditional patterns with if', 84),
  ('advanced-grammar-in-use-4-u85', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'If I were you ...; imagine he were to win', 85),
  ('advanced-grammar-in-use-4-u86', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'If ... not and unless; if and whether; etc.', 86),
  ('advanced-grammar-in-use-4-u87', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s12', 'Connecting ideas in a sentence and between sentences', 87),
  ('advanced-grammar-in-use-4-u88', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Prepositions of position and movement', 88),
  ('advanced-grammar-in-use-4-u89', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Between and among', 89),
  ('advanced-grammar-in-use-4-u90', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Prepositions of time', 90),
  ('advanced-grammar-in-use-4-u91', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Talking about exceptions', 91),
  ('advanced-grammar-in-use-4-u92', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Prepositions after verbs', 92),
  ('advanced-grammar-in-use-4-u93', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Prepositions after nouns', 93),
  ('advanced-grammar-in-use-4-u94', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s13', 'Multi-word verbs: word order', 94),
  ('advanced-grammar-in-use-4-u95', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s14', 'There is, there was, etc.', 95),
  ('advanced-grammar-in-use-4-u96', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s14', 'It as subject (introductory It)', 96),
  ('advanced-grammar-in-use-4-u97', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s14', 'It as object (referring forward): It is / was no versus There is / was no ...', 97),
  ('advanced-grammar-in-use-4-u98', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s14', 'Focusing: it-clauses and what-clauses', 98),
  ('advanced-grammar-in-use-4-u99-100', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s14', 'Inversion', 99),
  ('advanced-grammar-in-use-4-u101', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s15', 'Complex noun phrases and complex prepositions', 101),
  ('advanced-grammar-in-use-4-u102', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s15', 'Expressing and reporting opinions: it-clauses', 102),
  ('advanced-grammar-in-use-4-u103', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s15', 'Linking ideas in academic writing and speech', 103),
  ('advanced-grammar-in-use-4-u104', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s15', 'Referring to other work and sections in academic writing and speaking', 104),
  ('advanced-grammar-in-use-4-u105', 'grammar_in_use', 'advanced-grammar-in-use-4', 'advanced-grammar-in-use-4-s15', 'Academic discussion: lead-in phrases', 105);

INSERT INTO "GrammarKnowledgePointUnit" ("knowledgePointId", "unitNumber", "officialTitle") VALUES
  ('essential-grammar-in-use-4-u1', 1, 'am/is/are'),
  ('essential-grammar-in-use-4-u2', 2, 'am/is/are (questions)'),
  ('essential-grammar-in-use-4-u3', 3, 'I am doing (present continuous)'),
  ('essential-grammar-in-use-4-u4', 4, 'are you doing? (present continuous questions)'),
  ('essential-grammar-in-use-4-u5', 5, 'I do/work/like etc. (present simple)'),
  ('essential-grammar-in-use-4-u6', 6, 'I don’t ... (present simple negative)'),
  ('essential-grammar-in-use-4-u7', 7, 'Do you ... ? (present simple questions)'),
  ('essential-grammar-in-use-4-u8', 8, 'I am doing (present continuous) and I do (present simple)'),
  ('essential-grammar-in-use-4-u9', 9, 'I have ... and I’ve got ...'),
  ('essential-grammar-in-use-4-u10', 10, 'was/were'),
  ('essential-grammar-in-use-4-u11', 11, 'worked/got/went etc. (past simple)'),
  ('essential-grammar-in-use-4-u12', 12, 'I didn’t ... Did you ... ? (past simple negative and questions)'),
  ('essential-grammar-in-use-4-u13', 13, 'I was doing (past continuous)'),
  ('essential-grammar-in-use-4-u14', 14, 'I was doing (past continuous) and I did (past simple)'),
  ('essential-grammar-in-use-4-u15', 15, 'I have done (present perfect 1)'),
  ('essential-grammar-in-use-4-u16', 16, 'I’ve just ... I’ve already ... I haven’t ... yet (present perfect 2)'),
  ('essential-grammar-in-use-4-u17', 17, 'Have you ever ... ? (present perfect 3)'),
  ('essential-grammar-in-use-4-u18', 18, 'How long have you ... ? (present perfect 4)'),
  ('essential-grammar-in-use-4-u19', 19, 'for since ago'),
  ('essential-grammar-in-use-4-u20', 20, 'I have done (present perfect) and I did (past)'),
  ('essential-grammar-in-use-4-u21', 21, 'is done was done (passive 1)'),
  ('essential-grammar-in-use-4-u22', 22, 'is being done has been done (passive 2)'),
  ('essential-grammar-in-use-4-u23', 23, 'be/have/do in present and past tenses'),
  ('essential-grammar-in-use-4-u24', 24, 'Regular and irregular verbs'),
  ('essential-grammar-in-use-4-u25', 25, 'What are you doing tomorrow?'),
  ('essential-grammar-in-use-4-u26', 26, 'I’m going to ...'),
  ('essential-grammar-in-use-4-u27-28', 27, 'will/shall 1'),
  ('essential-grammar-in-use-4-u27-28', 28, 'will/shall 2'),
  ('essential-grammar-in-use-4-u29', 29, 'might'),
  ('essential-grammar-in-use-4-u30', 30, 'can and could'),
  ('essential-grammar-in-use-4-u31', 31, 'must mustn’t don’t need to'),
  ('essential-grammar-in-use-4-u32', 32, 'should'),
  ('essential-grammar-in-use-4-u33', 33, 'I have to ...'),
  ('essential-grammar-in-use-4-u34', 34, 'Would you like ... ? I’d like ...'),
  ('essential-grammar-in-use-4-u35', 35, 'Do this! Don’t do that! Let’s do this!'),
  ('essential-grammar-in-use-4-u36', 36, 'I used to ...'),
  ('essential-grammar-in-use-4-u37', 37, 'there is there are'),
  ('essential-grammar-in-use-4-u38', 38, 'there was/were there has/have been there will be'),
  ('essential-grammar-in-use-4-u39', 39, 'It ...'),
  ('essential-grammar-in-use-4-u40', 40, 'I am, I don’t etc.'),
  ('essential-grammar-in-use-4-u41', 41, 'Have you? Are you? Don’t you? etc.'),
  ('essential-grammar-in-use-4-u42', 42, 'too/either so am I / neither do I etc.'),
  ('essential-grammar-in-use-4-u43', 43, 'isn’t, haven’t, don’t etc. (negatives)'),
  ('essential-grammar-in-use-4-u44', 44, 'is it ... ? have you ... ? do they ... ? etc. (questions 1)'),
  ('essential-grammar-in-use-4-u45', 45, 'Who saw you? Who did you see? (questions 2)'),
  ('essential-grammar-in-use-4-u46', 46, 'Who is she talking to? What is it like? (questions 3)'),
  ('essential-grammar-in-use-4-u47', 47, 'What ... ? Which ... ? How ... ? (questions 4)'),
  ('essential-grammar-in-use-4-u48', 48, 'How long does it take ... ?'),
  ('essential-grammar-in-use-4-u49', 49, 'Do you know where ... ? I don’t know what ... etc.'),
  ('essential-grammar-in-use-4-u50', 50, 'She said that ... He told me that ...'),
  ('essential-grammar-in-use-4-u51', 51, 'work/working go/going do/doing'),
  ('essential-grammar-in-use-4-u52', 52, 'to ... (I want to do) and -ing (I enjoy doing)'),
  ('essential-grammar-in-use-4-u53', 53, 'I want you to ... I told you to ...'),
  ('essential-grammar-in-use-4-u54', 54, 'I went to the shop to ...'),
  ('essential-grammar-in-use-4-u55', 55, 'go to ... go on ... go for ... go -ing'),
  ('essential-grammar-in-use-4-u56', 56, 'get'),
  ('essential-grammar-in-use-4-u57', 57, 'do and make'),
  ('essential-grammar-in-use-4-u58', 58, 'have'),
  ('essential-grammar-in-use-4-u59', 59, 'I/me he/him they/them etc.'),
  ('essential-grammar-in-use-4-u60', 60, 'my/his/their etc.'),
  ('essential-grammar-in-use-4-u61', 61, 'Whose is this? It’s mine/yours/hers etc.'),
  ('essential-grammar-in-use-4-u62', 62, 'I/me/my/mine'),
  ('essential-grammar-in-use-4-u63', 63, 'myself/yourself/themselves etc.'),
  ('essential-grammar-in-use-4-u64', 64, '-’s (Kate’s camera / my brother’s car etc.)'),
  ('essential-grammar-in-use-4-u65', 65, 'a/an ...'),
  ('essential-grammar-in-use-4-u66', 66, 'train(s) bus(es) (singular and plural)'),
  ('essential-grammar-in-use-4-u67', 67, 'a bottle / some water (countable/uncountable 1)'),
  ('essential-grammar-in-use-4-u68', 68, 'a cake / some cake / some cakes (countable/uncountable 2)'),
  ('essential-grammar-in-use-4-u69', 69, 'a/an and the'),
  ('essential-grammar-in-use-4-u70', 70, 'the ...'),
  ('essential-grammar-in-use-4-u71', 71, 'go to work go home go to the cinema'),
  ('essential-grammar-in-use-4-u72', 72, 'I like music I hate exams'),
  ('essential-grammar-in-use-4-u73', 73, 'the ... (names of places)'),
  ('essential-grammar-in-use-4-u74', 74, 'this/that/these/those'),
  ('essential-grammar-in-use-4-u75', 75, 'one/ones'),
  ('essential-grammar-in-use-4-u76', 76, 'some and any'),
  ('essential-grammar-in-use-4-u77', 77, 'not + any no none'),
  ('essential-grammar-in-use-4-u78', 78, 'not + anybody/anyone/anything nobody/no-one/nothing'),
  ('essential-grammar-in-use-4-u79', 79, 'somebody/anything/nowhere etc.'),
  ('essential-grammar-in-use-4-u80', 80, 'every and all'),
  ('essential-grammar-in-use-4-u81', 81, 'all most some any no/none'),
  ('essential-grammar-in-use-4-u82', 82, 'both either neither'),
  ('essential-grammar-in-use-4-u83', 83, 'a lot much many'),
  ('essential-grammar-in-use-4-u84', 84, '(a) little (a) few'),
  ('essential-grammar-in-use-4-u85', 85, 'old/nice/interesting etc. (adjectives)'),
  ('essential-grammar-in-use-4-u86', 86, 'quickly/badly/suddenly etc. (adverbs)'),
  ('essential-grammar-in-use-4-u87', 87, 'old/older expensive / more expensive'),
  ('essential-grammar-in-use-4-u88', 88, 'older than ... more expensive than ...'),
  ('essential-grammar-in-use-4-u89', 89, 'not as ... as'),
  ('essential-grammar-in-use-4-u90', 90, 'the oldest the most expensive'),
  ('essential-grammar-in-use-4-u91', 91, 'enough'),
  ('essential-grammar-in-use-4-u92', 92, 'too'),
  ('essential-grammar-in-use-4-u93', 93, 'He speaks English very well. (word order 1)'),
  ('essential-grammar-in-use-4-u94', 94, 'always/usually/often etc. (word order 2)'),
  ('essential-grammar-in-use-4-u95', 95, 'still yet already'),
  ('essential-grammar-in-use-4-u96', 96, 'Give me that book! Give it to me!'),
  ('essential-grammar-in-use-4-u97', 97, 'and but or so because'),
  ('essential-grammar-in-use-4-u98', 98, 'When ...'),
  ('essential-grammar-in-use-4-u99', 99, 'If we go ... If you see ... etc.'),
  ('essential-grammar-in-use-4-u100', 100, 'If I had ... If we went ... etc.'),
  ('essential-grammar-in-use-4-u101', 101, 'a person who ... a thing that/which ... (relative clauses 1)'),
  ('essential-grammar-in-use-4-u102', 102, 'the people we met the hotel you stayed at (relative clauses 2)'),
  ('essential-grammar-in-use-4-u103', 103, 'at 8 o’clock on Monday in April'),
  ('essential-grammar-in-use-4-u104', 104, 'from ... to until since for'),
  ('essential-grammar-in-use-4-u105', 105, 'before after during while'),
  ('essential-grammar-in-use-4-u106', 106, 'in at on (places 1)'),
  ('essential-grammar-in-use-4-u107', 107, 'in at on (places 2)'),
  ('essential-grammar-in-use-4-u108', 108, 'to in at (places 3)'),
  ('essential-grammar-in-use-4-u109', 109, 'under, behind, opposite etc.'),
  ('essential-grammar-in-use-4-u110', 110, 'up, over, through etc.'),
  ('essential-grammar-in-use-4-u111', 111, 'on at by with about'),
  ('essential-grammar-in-use-4-u112', 112, 'afraid of ..., good at ... etc. of/at/for etc. (prepositions) + -ing'),
  ('essential-grammar-in-use-4-u113', 113, 'listen to ..., look at ... etc. (verb + preposition)'),
  ('essential-grammar-in-use-4-u114', 114, 'go in, fall off, run away etc. (phrasal verbs 1)'),
  ('essential-grammar-in-use-4-u115', 115, 'put on your shoes put your shoes on (phrasal verbs 2)'),
  ('english-grammar-in-use-5-u1', 1, 'Present continuous (I am doing)'),
  ('english-grammar-in-use-5-u2', 2, 'Present simple (I do)'),
  ('english-grammar-in-use-5-u3-4', 3, 'Present continuous and present simple 1 (I am doing and I do)'),
  ('english-grammar-in-use-5-u3-4', 4, 'Present continuous and present simple 2 (I am doing and I do)'),
  ('english-grammar-in-use-5-u5', 5, 'Past simple (I did)'),
  ('english-grammar-in-use-5-u6', 6, 'Past continuous (I was doing)'),
  ('english-grammar-in-use-5-u7-8', 7, 'Present perfect 1 (I have done)'),
  ('english-grammar-in-use-5-u7-8', 8, 'Present perfect 2 (I have done)'),
  ('english-grammar-in-use-5-u9', 9, 'Present perfect continuous (I have been doing)'),
  ('english-grammar-in-use-5-u10', 10, 'Present perfect continuous and simple (I have been doing and I have done)'),
  ('english-grammar-in-use-5-u11', 11, 'how long have you (been) ... ?'),
  ('english-grammar-in-use-5-u12', 12, 'for and since when ... ? and how long ... ?'),
  ('english-grammar-in-use-5-u13-14', 13, 'Present perfect and past 1 (I have done and I did)'),
  ('english-grammar-in-use-5-u13-14', 14, 'Present perfect and past 2 (I have done and I did)'),
  ('english-grammar-in-use-5-u15', 15, 'Past perfect (I had done)'),
  ('english-grammar-in-use-5-u16', 16, 'Past perfect continuous (I had been doing)'),
  ('english-grammar-in-use-5-u17', 17, 'have and have got'),
  ('english-grammar-in-use-5-u18', 18, 'used to (do)'),
  ('english-grammar-in-use-5-u19', 19, 'Present tenses (I am doing / I do) for the future'),
  ('english-grammar-in-use-5-u20', 20, 'I’m going to (do)'),
  ('english-grammar-in-use-5-u21-22', 21, 'will and shall 1'),
  ('english-grammar-in-use-5-u21-22', 22, 'will and shall 2'),
  ('english-grammar-in-use-5-u23', 23, 'I will and I’m going to'),
  ('english-grammar-in-use-5-u24', 24, 'will be doing and will have done'),
  ('english-grammar-in-use-5-u25', 25, 'when I do and when I’ve done if and when'),
  ('english-grammar-in-use-5-u26', 26, 'can, could and (be) able to'),
  ('english-grammar-in-use-5-u27', 27, 'could (do) and could have (done)'),
  ('english-grammar-in-use-5-u28', 28, 'must and can’t'),
  ('english-grammar-in-use-5-u29-30', 29, 'may and might 1'),
  ('english-grammar-in-use-5-u29-30', 30, 'may and might 2'),
  ('english-grammar-in-use-5-u31', 31, 'have to and must'),
  ('english-grammar-in-use-5-u32', 32, 'must mustn’t needn’t'),
  ('english-grammar-in-use-5-u33-34', 33, 'should 1'),
  ('english-grammar-in-use-5-u33-34', 34, 'should 2'),
  ('english-grammar-in-use-5-u35', 35, '’d better ... it’s time ...'),
  ('english-grammar-in-use-5-u36', 36, 'would'),
  ('english-grammar-in-use-5-u37', 37, 'can/could/would you ... ? etc. (Requests, offers, permission and invitations)'),
  ('english-grammar-in-use-5-u38', 38, 'if I do ... and if I did ...'),
  ('english-grammar-in-use-5-u39', 39, 'if I knew ... I wish I knew ...'),
  ('english-grammar-in-use-5-u40', 40, 'if I had known ... I wish I had known ...'),
  ('english-grammar-in-use-5-u41', 41, 'wish'),
  ('english-grammar-in-use-5-u42', 42, 'Passive 1 (is done / was done)'),
  ('english-grammar-in-use-5-u43', 43, 'Passive 2 (be done / been done / being done)'),
  ('english-grammar-in-use-5-u44', 44, 'Passive 3'),
  ('english-grammar-in-use-5-u45', 45, 'it is said that ... he is said to ... he is supposed to ...'),
  ('english-grammar-in-use-5-u46', 46, 'have something done'),
  ('english-grammar-in-use-5-u47', 47, 'Reported speech 1 (he said that ...)'),
  ('english-grammar-in-use-5-u48', 48, 'Reported speech 2'),
  ('english-grammar-in-use-5-u49', 49, 'Questions 1'),
  ('english-grammar-in-use-5-u50', 50, 'Questions 2 (do you know where ... ? / he asked me where ...)'),
  ('english-grammar-in-use-5-u51', 51, 'Auxiliary verbs (have/do/can etc.) I think so / I hope so etc.'),
  ('english-grammar-in-use-5-u52', 52, 'Question tags (do you? isn’t it? etc.)'),
  ('english-grammar-in-use-5-u53', 53, 'Verb + -ing (enjoy doing / stop doing etc.)'),
  ('english-grammar-in-use-5-u54', 54, 'Verb + to ... (decide to ... / forget to ... etc.)'),
  ('english-grammar-in-use-5-u55', 55, 'Verb (+ object) + to ... (I want you to ...)'),
  ('english-grammar-in-use-5-u56', 56, 'Verb + -ing or to ... 1 (remember, regret etc.)'),
  ('english-grammar-in-use-5-u57', 57, 'Verb + -ing or to ... 2 (try, need, help)'),
  ('english-grammar-in-use-5-u58', 58, 'Verb + -ing or to ... 3 (like / would like etc.)'),
  ('english-grammar-in-use-5-u59', 59, 'prefer and would rather'),
  ('english-grammar-in-use-5-u60', 60, 'Preposition (in/for/about etc.) + -ing'),
  ('english-grammar-in-use-5-u61', 61, 'be/get used to ... (I’m used to ...)'),
  ('english-grammar-in-use-5-u62', 62, 'Verb + preposition + -ing (succeed in -ing / insist on -ing etc.)'),
  ('english-grammar-in-use-5-u63', 63, 'there’s no point in -ing, it’s worth -ing etc.'),
  ('english-grammar-in-use-5-u64', 64, 'to ..., for ... and so that ...'),
  ('english-grammar-in-use-5-u65', 65, 'Adjective + to ...'),
  ('english-grammar-in-use-5-u66', 66, 'to ... (afraid to do) and preposition + -ing (afraid of -ing)'),
  ('english-grammar-in-use-5-u67', 67, 'see somebody do and see somebody doing'),
  ('english-grammar-in-use-5-u68', 68, '-ing clauses (He hurt his knee playing football.)'),
  ('english-grammar-in-use-5-u69-70', 69, 'Countable and uncountable 1'),
  ('english-grammar-in-use-5-u69-70', 70, 'Countable and uncountable 2'),
  ('english-grammar-in-use-5-u71', 71, 'Countable nouns with a/an and some'),
  ('english-grammar-in-use-5-u72', 72, 'a/an and the'),
  ('english-grammar-in-use-5-u73', 73, 'the 1'),
  ('english-grammar-in-use-5-u74', 74, 'the 2 (school / the school etc.)'),
  ('english-grammar-in-use-5-u75', 75, 'the 3 (children / the children)'),
  ('english-grammar-in-use-5-u76', 76, 'the 4 (the giraffe / the telephone / the old etc.)'),
  ('english-grammar-in-use-5-u77-78', 77, 'Names with and without the 1'),
  ('english-grammar-in-use-5-u77-78', 78, 'Names with and without the 2'),
  ('english-grammar-in-use-5-u79', 79, 'Singular and plural'),
  ('english-grammar-in-use-5-u80', 80, 'Noun + noun (a bus driver / a headache)'),
  ('english-grammar-in-use-5-u81', 81, '-’s (your sister’s name) and of ... (the name of the book)'),
  ('english-grammar-in-use-5-u82', 82, 'myself/yourself/themselves etc.'),
  ('english-grammar-in-use-5-u83', 83, 'a friend of mine my own house on my own/by myself'),
  ('english-grammar-in-use-5-u84', 84, 'there ... and it ...'),
  ('english-grammar-in-use-5-u85', 85, 'some and any'),
  ('english-grammar-in-use-5-u86', 86, 'no/none/any nothing/nobody etc.'),
  ('english-grammar-in-use-5-u87', 87, 'much, many, little, few, a lot, plenty'),
  ('english-grammar-in-use-5-u88', 88, 'all/all of most/most of no/none of etc.'),
  ('english-grammar-in-use-5-u89', 89, 'both/both of neither/neither of either/either of'),
  ('english-grammar-in-use-5-u90', 90, 'all every whole'),
  ('english-grammar-in-use-5-u91', 91, 'each and every'),
  ('english-grammar-in-use-5-u92', 92, 'Relative clauses 1: clauses with who/that/which'),
  ('english-grammar-in-use-5-u93', 93, 'Relative clauses 2: clauses with and without who/that/which'),
  ('english-grammar-in-use-5-u94', 94, 'Relative clauses 3: whose/whom/where'),
  ('english-grammar-in-use-5-u95', 95, 'Relative clauses 4: extra information clauses (1)'),
  ('english-grammar-in-use-5-u96', 96, 'Relative clauses 5: extra information clauses (2)'),
  ('english-grammar-in-use-5-u97', 97, '-ing and -ed clauses (the woman talking to Tom, the boy injured in the accident)'),
  ('english-grammar-in-use-5-u98', 98, 'Adjectives ending in -ing and -ed (boring/bored etc.)'),
  ('english-grammar-in-use-5-u99', 99, 'Adjectives: a nice new house, you look tired'),
  ('english-grammar-in-use-5-u100', 100, 'Adjectives and adverbs 1 (quick/quickly)'),
  ('english-grammar-in-use-5-u101', 101, 'Adjectives and adverbs 2 (well, fast, late, hard/hardly)'),
  ('english-grammar-in-use-5-u102', 102, 'so and such'),
  ('english-grammar-in-use-5-u103', 103, 'enough and too'),
  ('english-grammar-in-use-5-u104', 104, 'quite, pretty, rather and fairly'),
  ('english-grammar-in-use-5-u105', 105, 'Comparative 1 (cheaper, more expensive etc.)'),
  ('english-grammar-in-use-5-u106', 106, 'Comparative 2 (much better / any better etc.)'),
  ('english-grammar-in-use-5-u107', 107, 'Comparative 3 (as ... as / than)'),
  ('english-grammar-in-use-5-u108', 108, 'Superlative (the longest, the most enjoyable etc.)'),
  ('english-grammar-in-use-5-u109', 109, 'Word order 1: verb + object; place and time'),
  ('english-grammar-in-use-5-u110', 110, 'Word order 2: adverbs with the verb'),
  ('english-grammar-in-use-5-u111', 111, 'still anymore yet already'),
  ('english-grammar-in-use-5-u112', 112, 'even'),
  ('english-grammar-in-use-5-u113', 113, 'although though even though in spite of despite'),
  ('english-grammar-in-use-5-u114', 114, 'in case'),
  ('english-grammar-in-use-5-u115', 115, 'unless as long as provided'),
  ('english-grammar-in-use-5-u116', 116, 'as (as I walked ... / as I was ... etc.)'),
  ('english-grammar-in-use-5-u117', 117, 'like and as'),
  ('english-grammar-in-use-5-u118', 118, 'like as if'),
  ('english-grammar-in-use-5-u119', 119, 'during for while'),
  ('english-grammar-in-use-5-u120', 120, 'by and until by the time ...'),
  ('english-grammar-in-use-5-u121', 121, 'at/on/in (time)'),
  ('english-grammar-in-use-5-u122', 122, 'on time and in time at the end and in the end'),
  ('english-grammar-in-use-5-u123-125', 123, 'in/at/on (position) 1'),
  ('english-grammar-in-use-5-u123-125', 124, 'in/at/on (position) 2'),
  ('english-grammar-in-use-5-u123-125', 125, 'in/at/on (position) 3'),
  ('english-grammar-in-use-5-u126', 126, 'to, at, in and into'),
  ('english-grammar-in-use-5-u127', 127, 'in/on/at (other uses)'),
  ('english-grammar-in-use-5-u128', 128, 'by'),
  ('english-grammar-in-use-5-u129', 129, 'Noun + preposition (reason for, cause of etc.)'),
  ('english-grammar-in-use-5-u130-131', 130, 'Adjective + preposition 1'),
  ('english-grammar-in-use-5-u130-131', 131, 'Adjective + preposition 2'),
  ('english-grammar-in-use-5-u132', 132, 'Verb + preposition 1 to and at'),
  ('english-grammar-in-use-5-u133', 133, 'Verb + preposition 2 about/for/of/after'),
  ('english-grammar-in-use-5-u134', 134, 'Verb + preposition 3 about and of'),
  ('english-grammar-in-use-5-u135', 135, 'Verb + preposition 4 of/for/from/on'),
  ('english-grammar-in-use-5-u136', 136, 'Verb + preposition 5 in/into/with/to/on'),
  ('english-grammar-in-use-5-u137', 137, 'Phrasal verbs 1 Introduction'),
  ('english-grammar-in-use-5-u138', 138, 'Phrasal verbs 2 in/out'),
  ('english-grammar-in-use-5-u139', 139, 'Phrasal verbs 3 out'),
  ('english-grammar-in-use-5-u140', 140, 'Phrasal verbs 4 on/off (1)'),
  ('english-grammar-in-use-5-u141', 141, 'Phrasal verbs 5 on/off (2)'),
  ('english-grammar-in-use-5-u142', 142, 'Phrasal verbs 6 up/down'),
  ('english-grammar-in-use-5-u143', 143, 'Phrasal verbs 7 up (1)'),
  ('english-grammar-in-use-5-u144', 144, 'Phrasal verbs 8 up (2)'),
  ('english-grammar-in-use-5-u145', 145, 'Phrasal verbs 9 away/back'),
  ('advanced-grammar-in-use-4-u1', 1, 'Present continuous and present simple: state verbs and performatives'),
  ('advanced-grammar-in-use-4-u2', 2, 'Using present continuous and present simple'),
  ('advanced-grammar-in-use-4-u3', 3, 'Past simple and present perfect'),
  ('advanced-grammar-in-use-4-u4', 4, 'Past continuous and past simple'),
  ('advanced-grammar-in-use-4-u5', 5, 'Past perfect and past simple'),
  ('advanced-grammar-in-use-4-u6', 6, 'Present perfect continuous and present perfect'),
  ('advanced-grammar-in-use-4-u7', 7, 'Past perfect continuous, past perfect and past continuous'),
  ('advanced-grammar-in-use-4-u8', 8, 'Present and past time: review'),
  ('advanced-grammar-in-use-4-u9', 9, 'Will and be going to'),
  ('advanced-grammar-in-use-4-u10', 10, 'Present simple and present continuous for the future'),
  ('advanced-grammar-in-use-4-u11', 11, 'Future continuous, future perfect and future perfect continuous'),
  ('advanced-grammar-in-use-4-u12', 12, 'Be to + infinitive; be about to + infinitive'),
  ('advanced-grammar-in-use-4-u13', 13, 'Other ways of talking about the future'),
  ('advanced-grammar-in-use-4-u14', 14, 'The future seen from the past'),
  ('advanced-grammar-in-use-4-u15', 15, 'Can, could, be able to and be allowed to'),
  ('advanced-grammar-in-use-4-u16', 16, 'Will, would and used to'),
  ('advanced-grammar-in-use-4-u17', 17, 'May and might'),
  ('advanced-grammar-in-use-4-u18', 18, 'Must and have (got) to'),
  ('advanced-grammar-in-use-4-u19', 19, 'Need(n’t), don’t need to and don’t have to'),
  ('advanced-grammar-in-use-4-u20', 20, 'Should, ought to and had better'),
  ('advanced-grammar-in-use-4-u21', 21, 'Linking verbs: be, appear, seem; become, get, etc.'),
  ('advanced-grammar-in-use-4-u22', 22, 'Using passives'),
  ('advanced-grammar-in-use-4-u23', 23, 'Forming passive sentences: objects, complements and multi-word verbs'),
  ('advanced-grammar-in-use-4-u24', 24, 'Forming passive sentences: verb + -ing or to-infinitive'),
  ('advanced-grammar-in-use-4-u25', 25, 'Reporting with passives; It is said that ...'),
  ('advanced-grammar-in-use-4-u26', 26, 'Wh-questions with who, whom, which, how and whose'),
  ('advanced-grammar-in-use-4-u27', 27, 'Negative questions; echo questions; questions with that-clauses'),
  ('advanced-grammar-in-use-4-u28', 28, 'Verbs, objects and complements'),
  ('advanced-grammar-in-use-4-u29', 29, 'Verb + two objects'),
  ('advanced-grammar-in-use-4-u30-31', 30, 'Verb + -ing forms and infinitives 1'),
  ('advanced-grammar-in-use-4-u30-31', 31, 'Verb + -ing forms and infinitives 2'),
  ('advanced-grammar-in-use-4-u32', 32, 'Reporting people’s words and thoughts'),
  ('advanced-grammar-in-use-4-u33', 33, 'Reporting statements: that-clauses'),
  ('advanced-grammar-in-use-4-u34', 34, 'Verb + wh-clause'),
  ('advanced-grammar-in-use-4-u35', 35, 'Tense choice in reporting'),
  ('advanced-grammar-in-use-4-u36', 36, 'Reporting offers, suggestions, orders, intentions, etc.'),
  ('advanced-grammar-in-use-4-u37', 37, 'Modal verbs in reporting'),
  ('advanced-grammar-in-use-4-u38', 38, 'Reporting what people say using nouns and adjectives'),
  ('advanced-grammar-in-use-4-u39', 39, 'Should in that-clauses; the present subjunctive'),
  ('advanced-grammar-in-use-4-u40-42', 40, 'Agreement between subject and verb 1'),
  ('advanced-grammar-in-use-4-u40-42', 41, 'Agreement between subject and verb 2'),
  ('advanced-grammar-in-use-4-u40-42', 42, 'Agreement between subject and verb 3'),
  ('advanced-grammar-in-use-4-u43', 43, 'Compound nouns and noun phrases'),
  ('advanced-grammar-in-use-4-u44', 44, 'A/an and one'),
  ('advanced-grammar-in-use-4-u45-47', 45, 'A/an, the and zero article 1'),
  ('advanced-grammar-in-use-4-u45-47', 46, 'A/an, the and zero article 2'),
  ('advanced-grammar-in-use-4-u45-47', 47, 'A/an, the and zero article 3'),
  ('advanced-grammar-in-use-4-u48', 48, 'Some and any'),
  ('advanced-grammar-in-use-4-u49', 49, 'No, none (of) and not any'),
  ('advanced-grammar-in-use-4-u50', 50, 'Much (of), many (of), a lot of, lots (of), etc.'),
  ('advanced-grammar-in-use-4-u51', 51, 'All (of), whole, every, each'),
  ('advanced-grammar-in-use-4-u52', 52, 'Few, little, less, fewer'),
  ('advanced-grammar-in-use-4-u53', 53, 'Relative pronouns'),
  ('advanced-grammar-in-use-4-u54', 54, 'Other relative words: whose, when, whereby, etc.'),
  ('advanced-grammar-in-use-4-u55', 55, 'Prepositions in relative clauses'),
  ('advanced-grammar-in-use-4-u56', 56, 'Other ways of adding information to noun phrases 1: additional noun phrases, etc.'),
  ('advanced-grammar-in-use-4-u57', 57, 'Other ways of adding information to noun phrases 2: prepositional phrases, etc.'),
  ('advanced-grammar-in-use-4-u58-59', 58, 'Participle clauses with adverbial meaning 1'),
  ('advanced-grammar-in-use-4-u58-59', 59, 'Participle clauses with adverbial meaning 2'),
  ('advanced-grammar-in-use-4-u60', 60, 'Reflexive pronouns: herself, himself, themselves, etc.'),
  ('advanced-grammar-in-use-4-u61', 61, 'One and ones'),
  ('advanced-grammar-in-use-4-u62', 62, 'So and not as substitutes for clauses, etc.'),
  ('advanced-grammar-in-use-4-u63', 63, 'Do so; such'),
  ('advanced-grammar-in-use-4-u64', 64, 'More on ellipsis after auxiliary verbs'),
  ('advanced-grammar-in-use-4-u65', 65, 'Ellipsis of to-infinitives'),
  ('advanced-grammar-in-use-4-u66', 66, 'Position of adjectives'),
  ('advanced-grammar-in-use-4-u67', 67, 'Gradable and non-gradable adjectives: using adjectives with adverbs'),
  ('advanced-grammar-in-use-4-u68', 68, 'Gradable and non-gradable adjectives: differences in meaning'),
  ('advanced-grammar-in-use-4-u69', 69, 'Participle adjectives and compound adjectives'),
  ('advanced-grammar-in-use-4-u70', 70, 'Adjectives + to-infinitive, -ing, that-clause, wh-clause'),
  ('advanced-grammar-in-use-4-u71', 71, 'Adjectives and adverbs'),
  ('advanced-grammar-in-use-4-u72', 72, 'Adjectives and adverbs: comparative and superlative forms'),
  ('advanced-grammar-in-use-4-u73', 73, 'Comparative phrases and clauses'),
  ('advanced-grammar-in-use-4-u74', 74, 'Position of adverbs: end position'),
  ('advanced-grammar-in-use-4-u75', 75, 'Position of adverbs: front and mid position'),
  ('advanced-grammar-in-use-4-u76', 76, 'Adverbs of place, direction, indefinite frequency, and time'),
  ('advanced-grammar-in-use-4-u77', 77, 'Degree adverbs and focus adverbs'),
  ('advanced-grammar-in-use-4-u78', 78, 'Comment adverbs and viewpoint adverbs'),
  ('advanced-grammar-in-use-4-u79', 79, 'Adverbial clauses of time'),
  ('advanced-grammar-in-use-4-u80', 80, 'Giving reasons: as, because, etc.; for and with'),
  ('advanced-grammar-in-use-4-u81', 81, 'Purposes and results: in order to, so as to, etc.'),
  ('advanced-grammar-in-use-4-u82', 82, 'Contrasts: although and though; even though / if; while, whilst and whereas'),
  ('advanced-grammar-in-use-4-u83', 83, 'If: real and unreal conditionals'),
  ('advanced-grammar-in-use-4-u84', 84, 'If: other conditional patterns with if'),
  ('advanced-grammar-in-use-4-u85', 85, 'If I were you ...; imagine he were to win'),
  ('advanced-grammar-in-use-4-u86', 86, 'If ... not and unless; if and whether; etc.'),
  ('advanced-grammar-in-use-4-u87', 87, 'Connecting ideas in a sentence and between sentences'),
  ('advanced-grammar-in-use-4-u88', 88, 'Prepositions of position and movement'),
  ('advanced-grammar-in-use-4-u89', 89, 'Between and among'),
  ('advanced-grammar-in-use-4-u90', 90, 'Prepositions of time'),
  ('advanced-grammar-in-use-4-u91', 91, 'Talking about exceptions'),
  ('advanced-grammar-in-use-4-u92', 92, 'Prepositions after verbs'),
  ('advanced-grammar-in-use-4-u93', 93, 'Prepositions after nouns'),
  ('advanced-grammar-in-use-4-u94', 94, 'Multi-word verbs: word order'),
  ('advanced-grammar-in-use-4-u95', 95, 'There is, there was, etc.'),
  ('advanced-grammar-in-use-4-u96', 96, 'It as subject (introductory It)'),
  ('advanced-grammar-in-use-4-u97', 97, 'It as object (referring forward): It is / was no versus There is / was no ...'),
  ('advanced-grammar-in-use-4-u98', 98, 'Focusing: it-clauses and what-clauses'),
  ('advanced-grammar-in-use-4-u99-100', 99, 'Inversion 1'),
  ('advanced-grammar-in-use-4-u99-100', 100, 'Inversion 2'),
  ('advanced-grammar-in-use-4-u101', 101, 'Complex noun phrases and complex prepositions'),
  ('advanced-grammar-in-use-4-u102', 102, 'Expressing and reporting opinions: it-clauses'),
  ('advanced-grammar-in-use-4-u103', 103, 'Linking ideas in academic writing and speech'),
  ('advanced-grammar-in-use-4-u104', 104, 'Referring to other work and sections in academic writing and speaking'),
  ('advanced-grammar-in-use-4-u105', 105, 'Academic discussion: lead-in phrases');
